In [17]:
import numpy as np
import pandas as pd
import warnings
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
warnings.filterwarnings('ignore')
pd.set_option("display.max_rows", 10, "display.max_columns", 10)
from sklearn.metrics import mean_squared_error, confusion_matrix, accuracy_score
from xgboost import XGBClassifier
from sklearn.neural_network import MLPClassifier


In [25]:
with open("data/label8_eurusd_10bar_1500_500_val200_gaf_culr.pkl", 'rb') as f:
    data = pd.read_pickle(f)
    X = data["train_gaf"]
    X = X.reshape(X.shape[0], -1)
    y = np.array([i.argmax() for i in data['train_label_arr']])
    print(X.shape, y.shape)
    test = data["test_gaf"][:4500]
    test = test.reshape(test.shape[0], -1)
    test_label=np.array([i.argmax() for i in data['test_label_arr'][:4500]])

(15000, 400) (15000,)


ADABOOST CLASSIFIER

In [61]:
ada=AdaBoostClassifier()
ada.fit(X,y)

AdaBoostClassifier()

In [62]:
y_pred=ada.predict(test)
conf_mat = confusion_matrix(test_label, y_pred)
mse = mean_squared_error(test_label, y_pred)
acc_score = accuracy_score(test_label, y_pred)
print(mse)
print(acc_score)
print(conf_mat)

6.84
0.47955555555555557
[[178  19  49  64  41  85  20   0  44]
 [ 30 119   0 314   0  36   1   0   0]
 [ 31   0 411   0  33   1   3   0  21]
 [  0   7   0 480   0  13   0   0   0]
 [  1   0  60   0  97   0   2   0 340]
 [ 51   4   0  97   0 348   0   0   0]
 [ 35   0  50   0  85   1 119   0 210]
 [  0   2   0 461   0  37   0   0   0]
 [  1   0  42   0  49   0   2   0 406]]


RANDOM FOREST CLASSIFIER

In [19]:
clf = RandomForestClassifier()
clf.fit(X, y)

RandomForestClassifier()

In [35]:
y_pred=clf.predict(test)
conf_mat = confusion_matrix(test_label, y_pred)
mse = mean_squared_error(test_label, y_pred)
acc_score = accuracy_score(test_label, y_pred)
print(mse)
print(acc_score)
print(conf_mat)

2.732
0.8691111111111111
[[386   8  12  17  19  21  10  14  13]
 [ 26 470   0   4   0   0   0   0   0]
 [ 26   0 472   0   2   0   0   0   0]
 [ 35  11   0 409   0   0   0  45   0]
 [ 28   0  18   0 392   0   2   0  60]
 [ 38   0   0   0   0 457   0   5   0]
 [ 50   0   0   0   0   0 446   0   4]
 [ 19   0   0  28   0   7   0 446   0]
 [ 30   0   0   0  33   0   4   0 433]]


MLP CLASSIFIER

In [50]:
mlp = MLPClassifier(random_state=1, max_iter=300,hidden_layer_sizes=128)
mlp.fit(X, y)

MLPClassifier(hidden_layer_sizes=128, max_iter=300, random_state=1)

In [52]:
y_pred=mlp.predict(test)
conf_mat = confusion_matrix(test_label, y_pred)
mse = mean_squared_error(test_label, y_pred)
acc_score = accuracy_score(test_label, y_pred)
print(mse)
print(acc_score)
print(conf_mat)

3.2666666666666666
0.8548888888888889
[[380  12  17  14  20  18   9  18  12]
 [ 24 475   0   1   0   0   0   0   0]
 [ 27   0 469   0   3   0   0   0   1]
 [ 47   7   0 415   0   0   0  31   0]
 [ 47   0  12   0 384   0   0   0  57]
 [ 38   0   0   0   0 458   0   4   0]
 [ 57   0   1   0   0   0 428   0  14]
 [ 45   0   0  35   0   7   0 413   0]
 [ 40   0   0   0  27   0   8   0 425]]


In [53]:
xgb = XGBClassifier()
xgb.fit(X, y)

[23:21:52] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, enable_categorical=False,
              gamma=0, gpu_id=-1, importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_delta_step=0, max_depth=6, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=100, n_jobs=8,
              num_parallel_tree=1, objective='multi:softprob', predictor='auto',
              random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=None,
              subsample=1, tree_method='exact', validate_parameters=1,
              verbosity=None)

In [54]:
y_pred = xgb.predict(test)
y_pred = [round(value) for value in y_pred]
conf_mat = confusion_matrix(test_label, y_pred)
mse = mean_squared_error(test_label, y_pred)
acc_score = accuracy_score(test_label, y_pred)
print(mse)
print(acc_score)
print(conf_mat)

2.104
0.904
[[386  12  12  15  18  10  10  17  20]
 [ 19 478   0   3   0   0   0   0   0]
 [ 15   0 485   0   0   0   0   0   0]
 [ 36   9   0 430   0   0   0  25   0]
 [ 26   0   9   0 430   0   1   0  34]
 [ 21   0   0   0   0 476   0   3   0]
 [ 32   0   0   0   0   0 467   0   1]
 [ 22   0   0  17   0   1   0 460   0]
 [ 14   0   0   0  29   0   1   0 456]]
